#!/bin/bash
set -euo pipefail

if [[ $# -ne 0 ]]; then
    echo "Usage: $0" >&2
    exit 1
fi

BUILD_URL="${BUILD_URL:-unknown}"
: "${GIT_BRANCH:?GIT_BRANCH is required}"

git add manifests/ 2>/dev/null || true

if git diff --cached --quiet manifests/ 2>/dev/null && \
   [ -z "$(git status --porcelain manifests/ 2>/dev/null)" ]; then
    echo "No manifest changes to commit"
    exit 0
fi

echo "Committing generated manifests..."
git add manifests/
git commit -m "chore: regenerate manifests [jenkins-ci]

Generated by Jenkins CI.
Build: ${BUILD_URL}"

git push origin HEAD:"${GIT_BRANCH#origin/}" || {
    echo "ERROR: Failed to push generated manifests to feature branch"
    echo "Possible causes: force-push protection, auth failure, network error"
    exit 1
}

echo "Manifests committed and pushed"
