#!/bin/bash
# Demo: Platform Default with Environment Override (UC-C6)
#
# This demo showcases how environment-specific configuration can override
# platform-wide defaults through the CUE layering system.
#
# Use Case UC-C6:
# "Platform sets cost-center=platform-shared, but prod overrides to
# cost-center=production-critical for priority billing"
#
# What This Demonstrates:
# - Platform-wide defaults propagate to ALL environments (like UC-C1)
# - Environment-specific overrides in env.cue take precedence
# - Override only affects the target environment (isolation)
# - Promotion preserves environment-specific configuration
#
# Flow:
# 1. Add platform default (cost-center: platform-shared)
# 2. Promote through all environments (dev/stage/prod all get platform-shared)
# 3. Add prod override (cost-center: production-critical)
# 4. Verify: dev/stage have platform-shared, prod has production-critical
#
# Prerequisites:
# - Environment branches (dev/stage/prod) exist in GitLab
# - Pipeline infrastructure running (Jenkins, ArgoCD)
# - Run from deployment-pipeline root

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
K8S_DEPLOYMENTS_DIR="${PROJECT_ROOT}/k8s-deployments"

# Load helper libraries
source "${SCRIPT_DIR}/lib/demo-helpers.sh"
source "${SCRIPT_DIR}/lib/assertions.sh"
source "${SCRIPT_DIR}/lib/pipeline-wait.sh"

# ============================================================================
# CONFIGURATION
# ============================================================================

DEMO_LABEL_KEY="cost-center"
PLATFORM_LABEL_VALUE="platform-shared"
PROD_OVERRIDE_VALUE="production-critical"
DEMO_APP="example-app"
DEMO_APP_CUE="exampleApp"  # CUE identifier
ENVIRONMENTS=("dev" "stage" "prod")

# CUE edit helper path
CUE_EDIT="${SCRIPT_DIR}/lib/cue-edit.py"

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

add_platform_label() {
    demo_action "Adding platform label using cue-edit.py..."

    if ! python3 "${CUE_EDIT}" platform-label add "$DEMO_LABEL_KEY" "$PLATFORM_LABEL_VALUE"; then
        demo_fail "Failed to add platform label"
        return 1
    fi
    demo_verify "Added $DEMO_LABEL_KEY: $PLATFORM_LABEL_VALUE to defaultLabels"
    return 0
}

# ============================================================================
# MAIN DEMO
# ============================================================================

cd "$K8S_DEPLOYMENTS_DIR"

demo_init "UC-C6: Platform Default with Environment Override"

# Load credentials
load_pipeline_credentials || exit 1

# Save original branch
ORIGINAL_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main")

# Setup cleanup
demo_cleanup_on_exit "$ORIGINAL_BRANCH"

# ---------------------------------------------------------------------------
# Step 1: Verify Prerequisites
# ---------------------------------------------------------------------------

demo_step 1 "Verify Prerequisites"

demo_action "Checking kubectl connectivity..."
if ! kubectl cluster-info &>/dev/null; then
    demo_fail "Cannot connect to Kubernetes cluster"
    exit 1
fi
demo_verify "Connected to Kubernetes cluster"

demo_action "Checking ArgoCD applications..."
for env in "${ENVIRONMENTS[@]}"; do
    if kubectl get application "${DEMO_APP}-${env}" -n "${ARGOCD_NAMESPACE}" &>/dev/null; then
        demo_verify "ArgoCD app ${DEMO_APP}-${env} exists"
    else
        demo_fail "ArgoCD app ${DEMO_APP}-${env} not found"
        exit 1
    fi
done

# ---------------------------------------------------------------------------
# Step 2: Add Platform Default Label
# ---------------------------------------------------------------------------

demo_step 2 "Add Platform Default Label"

demo_info "Adding '$DEMO_LABEL_KEY: $PLATFORM_LABEL_VALUE' to services/core/app.cue"

# Make CUE change using cue-edit.py
add_platform_label || exit 1

demo_action "Summary of CUE changes:"
git diff --stat services/core/app.cue 2>/dev/null || echo "  (no diff available)"

# ---------------------------------------------------------------------------
# Step 3: Commit and Push Platform Default
# ---------------------------------------------------------------------------

demo_step 3 "Commit and Push Platform Default"

demo_action "Creating feature branch..."
FEATURE_BRANCH="uc-c6-platform-default-$(date +%s)"
git checkout -b "$FEATURE_BRANCH"

demo_action "Committing CUE change only (manifests generated by pipeline)..."
git add services/core/app.cue
git commit -m "feat: add $DEMO_LABEL_KEY label to all deployments (UC-C6)"

demo_action "Pushing feature branch to GitLab..."
cd "$PROJECT_ROOT"
git subtree push --prefix=k8s-deployments gitlab-deployments "$FEATURE_BRANCH"
cd "$K8S_DEPLOYMENTS_DIR"
demo_verify "Feature branch pushed"

# ---------------------------------------------------------------------------
# Step 4: Promote Platform Default Through All Environments
# ---------------------------------------------------------------------------

demo_step 4 "Promote Platform Default Through All Environments"

# Track baseline time for promotion MR detection
next_promotion_baseline=""

for env in "${ENVIRONMENTS[@]}"; do
    demo_info "--- Promoting to $env ---"

    # Capture baselines before MR
    argocd_baseline=$(get_argocd_revision "${DEMO_APP}-${env}")

    if [[ "$env" == "dev" ]]; then
        # DEV: Create MR from feature branch
        mr_iid=$(create_mr "$FEATURE_BRANCH" "$env" "UC-C6: Add $DEMO_LABEL_KEY label to $env")

        # Wait for MR pipeline
        demo_action "Waiting for pipeline to generate manifests..."
        wait_for_mr_pipeline "$mr_iid" || exit 1

        # Verify MR contains expected changes
        demo_action "Verifying MR contains CUE and manifest changes..."
        assert_mr_contains_diff "$mr_iid" "services/core/app.cue" "$DEMO_LABEL_KEY" || exit 1
        assert_mr_contains_diff "$mr_iid" "manifests/.*\\.yaml" "$DEMO_LABEL_KEY" || exit 1

        # Capture baseline time BEFORE merge
        next_promotion_baseline=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

        # Merge MR
        accept_mr "$mr_iid" || exit 1
    else
        # STAGE/PROD: Wait for Jenkins-created promotion MR
        wait_for_promotion_mr "$env" "$next_promotion_baseline" || exit 1
        mr_iid="$PROMOTION_MR_IID"

        # Wait for MR pipeline
        demo_action "Waiting for pipeline to validate promotion..."
        wait_for_mr_pipeline "$mr_iid" || exit 1

        # Verify MR contains expected changes
        demo_action "Verifying MR contains manifest changes..."
        assert_mr_contains_diff "$mr_iid" "manifests/.*\\.yaml" "$DEMO_LABEL_KEY" || exit 1

        # Capture baseline time BEFORE merge
        next_promotion_baseline=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

        # Merge MR
        accept_mr "$mr_iid" || exit 1
    fi

    # Wait for ArgoCD sync
    wait_for_argocd_sync "${DEMO_APP}-${env}" "$argocd_baseline" || exit 1

    # Verify K8s state
    demo_action "Verifying label in K8s deployment..."
    assert_pod_label_equals "$env" "$DEMO_APP" "$DEMO_LABEL_KEY" "$PLATFORM_LABEL_VALUE" || exit 1

    demo_verify "Promotion to $env complete"
    echo ""
done

# ---------------------------------------------------------------------------
# Step 5: Checkpoint - All Environments Have Platform Default
# ---------------------------------------------------------------------------

demo_step 5 "Checkpoint - All Environments Have Platform Default"

demo_info "Verifying platform default propagated to ALL environments..."

assert_env_propagation "deployment" "$DEMO_APP" \
    "{.spec.template.metadata.labels.$DEMO_LABEL_KEY}" \
    "$PLATFORM_LABEL_VALUE" \
    "${ENVIRONMENTS[@]}" || exit 1

demo_verify "CHECKPOINT: All environments have '$DEMO_LABEL_KEY: $PLATFORM_LABEL_VALUE'"
demo_info "This proves UC-C1-like behavior: platform-wide propagation works."
echo ""

# ---------------------------------------------------------------------------
# Step 6: Add Prod Override
# ---------------------------------------------------------------------------

demo_step 6 "Add Prod Override"

demo_info "Now adding override to prod: '$DEMO_LABEL_KEY: $PROD_OVERRIDE_VALUE'"

# Get current env.cue content from prod branch
demo_action "Fetching prod's env.cue from GitLab..."
PROD_ENV_CUE=$(get_file_from_branch "prod" "env.cue")

if [[ -z "$PROD_ENV_CUE" ]]; then
    demo_fail "Could not fetch env.cue from prod branch"
    exit 1
fi
demo_verify "Retrieved prod's env.cue"

# Modify the content locally using cue-edit.py
# Note: Create temp file in k8s-deployments so cue-edit.py can find CUE project context
demo_action "Adding label override to env.cue..."
TEMP_ENV_CUE="${K8S_DEPLOYMENTS_DIR}/.tmp-env-cue-$$.cue"
echo "$PROD_ENV_CUE" > "$TEMP_ENV_CUE"

# Use cue-edit.py to add the label
if ! python3 "${CUE_EDIT}" env-label add "$TEMP_ENV_CUE" "prod" "$DEMO_APP_CUE" "$DEMO_LABEL_KEY" "$PROD_OVERRIDE_VALUE"; then
    demo_fail "Failed to add label override to env.cue"
    rm -f "$TEMP_ENV_CUE"
    exit 1
fi

MODIFIED_ENV_CUE=$(cat "$TEMP_ENV_CUE")
rm -f "$TEMP_ENV_CUE"
demo_verify "Modified env.cue with override"

# Create branch and MR for the override
OVERRIDE_BRANCH="uc-c6-prod-override-$(date +%s)"
demo_action "Creating override branch: $OVERRIDE_BRANCH"

# Use GitLab API to create branch from prod
PROJECT="${DEPLOYMENTS_REPO_PATH:-p2c/k8s-deployments}"
ENCODED_PROJECT=$(echo "$PROJECT" | sed 's/\//%2F/g')

branch_result=$(curl -sk -X POST -H "PRIVATE-TOKEN: $GITLAB_TOKEN" \
    "${GITLAB_URL_EXTERNAL}/api/v4/projects/${ENCODED_PROJECT}/repository/branches?branch=${OVERRIDE_BRANCH}&ref=prod" 2>/dev/null)

if ! echo "$branch_result" | jq -e '.name' >/dev/null 2>&1; then
    demo_fail "Could not create branch: $(echo "$branch_result" | jq -r '.message // "unknown error"')"
    exit 1
fi
demo_verify "Created branch $OVERRIDE_BRANCH from prod"

# Commit the modified env.cue to the override branch
demo_action "Committing override to branch..."
commit_file_to_branch "$OVERRIDE_BRANCH" "env.cue" "$MODIFIED_ENV_CUE" \
    "feat: override $DEMO_LABEL_KEY to $PROD_OVERRIDE_VALUE in prod (UC-C6)" || exit 1

# Create MR from override branch to prod
demo_action "Creating MR for prod override..."
override_mr_iid=$(create_mr "$OVERRIDE_BRANCH" "prod" "UC-C6: Override $DEMO_LABEL_KEY in prod")

# Wait for MR pipeline
demo_action "Waiting for pipeline to validate override..."
wait_for_mr_pipeline "$override_mr_iid" || exit 1

# Verify MR contains expected changes
demo_action "Verifying MR contains override..."
assert_mr_contains_diff "$override_mr_iid" "env.cue" "$PROD_OVERRIDE_VALUE" || exit 1

# Capture ArgoCD baseline before merge
argocd_baseline=$(get_argocd_revision "${DEMO_APP}-prod")

# Merge MR
accept_mr "$override_mr_iid" || exit 1

# Wait for ArgoCD sync
wait_for_argocd_sync "${DEMO_APP}-prod" "$argocd_baseline" || exit 1

demo_verify "Prod override applied successfully"

# ---------------------------------------------------------------------------
# Step 7: Final Verification - Override Only Affects Prod
# ---------------------------------------------------------------------------

demo_step 7 "Final Verification - Override Only Affects Prod"

demo_info "Verifying final state across all environments..."

# Dev should still have platform default
demo_action "Checking dev..."
assert_pod_label_equals "dev" "$DEMO_APP" "$DEMO_LABEL_KEY" "$PLATFORM_LABEL_VALUE" || exit 1

# Stage should still have platform default
demo_action "Checking stage..."
assert_pod_label_equals "stage" "$DEMO_APP" "$DEMO_LABEL_KEY" "$PLATFORM_LABEL_VALUE" || exit 1

# Prod should have the override
demo_action "Checking prod..."
assert_pod_label_equals "prod" "$DEMO_APP" "$DEMO_LABEL_KEY" "$PROD_OVERRIDE_VALUE" || exit 1

demo_verify "VERIFIED: Environment isolation works correctly!"
demo_info "  - dev:   $DEMO_LABEL_KEY = $PLATFORM_LABEL_VALUE (platform default)"
demo_info "  - stage: $DEMO_LABEL_KEY = $PLATFORM_LABEL_VALUE (platform default)"
demo_info "  - prod:  $DEMO_LABEL_KEY = $PROD_OVERRIDE_VALUE (environment override)"

# ---------------------------------------------------------------------------
# Step 8: Summary
# ---------------------------------------------------------------------------

demo_step 8 "Summary"

cat << EOF

  This demo validated UC-C6: Platform Default with Environment Override

  What happened:
  1. Added '$DEMO_LABEL_KEY: $PLATFORM_LABEL_VALUE' to platform layer (services/core/app.cue)
  2. Promoted through all environments using GitOps pattern:
     - Feature branch -> dev: Manual MR (pipeline generates manifests)
     - dev -> stage: Jenkins auto-created promotion MR
     - stage -> prod: Jenkins auto-created promotion MR
  3. CHECKPOINT: Verified all environments had platform default
  4. Added prod override '$DEMO_LABEL_KEY: $PROD_OVERRIDE_VALUE' via MR
  5. Verified final state:
     - dev/stage: platform default ($PLATFORM_LABEL_VALUE)
     - prod: environment override ($PROD_OVERRIDE_VALUE)

  Key Observations:
  - Platform-wide defaults propagate correctly (UC-C1 behavior)
  - Environment overrides take precedence (CUE unification)
  - Override only affects target environment (isolation)
  - All changes go through MR with pipeline validation (GitOps)

  Override Hierarchy Validated:
    Platform (services/core/app.cue) -> sets default
        |
    Environment (env.cue on prod) -> overrides for prod only

EOF

# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------

demo_step 9 "Cleanup"

demo_action "Returning to original branch: $ORIGINAL_BRANCH"
git checkout "$ORIGINAL_BRANCH" 2>/dev/null || true

demo_info "Feature branch '$FEATURE_BRANCH' left in place for reference"
demo_info "Override branch '$OVERRIDE_BRANCH' left in place for reference"
demo_info "To delete locally: git branch -D $FEATURE_BRANCH"

demo_complete
