#!/bin/bash
# Demo: Add Default Label to All Deployments (UC-C1)
#
# This demo showcases how platform-wide changes propagate to all apps
# in all environments through the CUE layering system.
#
# Use Case UC-C1:
# "As a platform team, we need all deployments to have a cost-center label
# for chargeback reporting"
#
# What This Demonstrates:
# - Changes to services/core/ propagate to ALL apps in ALL environments
# - The MR shows both CUE change AND generated manifest changes
# - Pipeline generates manifests (not the human)
#
# Prerequisites:
# - Environment branches (dev/stage/prod) exist in GitLab
# - Pipeline infrastructure running (Jenkins, ArgoCD)
# - Run from deployment-pipeline root

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
K8S_DEPLOYMENTS_DIR="${PROJECT_ROOT}/k8s-deployments"

# Load helper libraries
source "${SCRIPT_DIR}/lib/demo-helpers.sh"
source "${SCRIPT_DIR}/lib/assertions.sh"
source "${SCRIPT_DIR}/lib/pipeline-wait.sh"

# ============================================================================
# CONFIGURATION
# ============================================================================

DEMO_LABEL_KEY="cost-center"
DEMO_LABEL_VALUE="platform-shared"
DEMO_APP="example-app"
ENVIRONMENTS=("dev" "stage" "prod")

# ============================================================================
# MAIN DEMO
# ============================================================================

cd "$K8S_DEPLOYMENTS_DIR"

demo_init "UC-C1: Add Default Label to All Deployments"

# Load credentials
load_pipeline_credentials || exit 1

# Save original branch
ORIGINAL_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main")

# Setup cleanup
demo_cleanup_on_exit "$ORIGINAL_BRANCH"

# ---------------------------------------------------------------------------
# Step 1: Verify Prerequisites
# ---------------------------------------------------------------------------

demo_step 1 "Verify Prerequisites"

demo_action "Checking kubectl connectivity..."
if ! kubectl cluster-info &>/dev/null; then
    demo_fail "Cannot connect to Kubernetes cluster"
    exit 1
fi
demo_verify "Connected to Kubernetes cluster"

demo_action "Checking ArgoCD applications..."
for env in "${ENVIRONMENTS[@]}"; do
    if kubectl get application "${DEMO_APP}-${env}" -n "${ARGOCD_NAMESPACE}" &>/dev/null; then
        demo_verify "ArgoCD app ${DEMO_APP}-${env} exists"
    else
        demo_fail "ArgoCD app ${DEMO_APP}-${env} not found"
        exit 1
    fi
done

# ---------------------------------------------------------------------------
# Step 2: Make CUE Change (Platform Layer)
# ---------------------------------------------------------------------------

demo_step 2 "Add Default Label to Platform Layer"

demo_info "Adding '$DEMO_LABEL_KEY: $DEMO_LABEL_VALUE' to services/core/app.cue"

# Check if label already exists
if grep -q "$DEMO_LABEL_KEY" services/core/app.cue; then
    demo_warn "Label '$DEMO_LABEL_KEY' already exists in app.cue"
    demo_info "Updating value to '$DEMO_LABEL_VALUE'"
fi

# Add/update the label in defaultLabels
# Using sed to add after the existing labels
if ! grep -q "$DEMO_LABEL_KEY" services/core/app.cue; then
    # Add new label after "deployment: appName"
    sed -i "/deployment: appName/a\\		\"$DEMO_LABEL_KEY\": \"$DEMO_LABEL_VALUE\"" services/core/app.cue
    demo_verify "Added label to services/core/app.cue"
else
    # Update existing label
    sed -i "s/\"$DEMO_LABEL_KEY\": \"[^\"]*\"/\"$DEMO_LABEL_KEY\": \"$DEMO_LABEL_VALUE\"/" services/core/app.cue
    demo_verify "Updated label in services/core/app.cue"
fi

# Verify the label was actually added/updated
if ! grep -q "\"$DEMO_LABEL_KEY\": \"$DEMO_LABEL_VALUE\"" services/core/app.cue; then
    demo_fail "Failed to add/update $DEMO_LABEL_KEY in app.cue"
    exit 1
fi

# Verify CUE is valid (use -c=false since main branch env.cue is incomplete by design)
demo_action "Validating CUE configuration..."
if cue vet -c=false ./...; then
    demo_verify "CUE validation passed"
else
    demo_fail "CUE validation failed"
    exit 1
fi

demo_action "Changed section in services/core/app.cue:"
grep -A5 "defaultLabels" services/core/app.cue | head -10 | sed 's/^/    /'

# ---------------------------------------------------------------------------
# Step 3: Commit and Push CUE Change
# ---------------------------------------------------------------------------

demo_step 3 "Commit and Push CUE Change"

demo_action "Creating feature branch..."
FEATURE_BRANCH="uc-c1-add-${DEMO_LABEL_KEY}-$(date +%s)"
git checkout -b "$FEATURE_BRANCH"

demo_action "Committing CUE change only (manifests generated by pipeline)..."
git add services/core/app.cue
git commit -m "feat: add $DEMO_LABEL_KEY label to all deployments (UC-C1)"

demo_action "Pushing feature branch to GitLab..."
# Use subtree push to push only k8s-deployments to GitLab
# Note: Must be run from repo root, not k8s-deployments directory
cd "$PROJECT_ROOT"
git subtree push --prefix=k8s-deployments gitlab-deployments "$FEATURE_BRANCH"
cd "$K8S_DEPLOYMENTS_DIR"
demo_verify "Feature branch pushed"

# ---------------------------------------------------------------------------
# Step 4: MR-Gated Promotion Through Environments
# ---------------------------------------------------------------------------

demo_step 4 "MR-Gated Promotion Through Environments"

for env in "${ENVIRONMENTS[@]}"; do
    demo_info "--- Promoting to $env ---"

    # Capture baselines before MR
    jenkins_baseline=$(get_jenkins_build_number "$env")
    argocd_baseline=$(get_argocd_revision "${DEMO_APP}-${env}")

    # Create MR
    mr_iid=$(create_mr "$FEATURE_BRANCH" "$env" "UC-C1: Add $DEMO_LABEL_KEY label to $env")

    # Wait for MR pipeline (generates manifests)
    demo_action "Waiting for pipeline to generate manifests..."
    wait_for_mr_pipeline "$mr_iid" || exit 1

    # Verify MR contains expected changes
    demo_action "Verifying MR contains CUE and manifest changes..."
    assert_mr_contains_diff "$mr_iid" "services/core/app.cue" "$DEMO_LABEL_KEY" || exit 1
    assert_mr_contains_diff "$mr_iid" "manifests/.*\\.yaml" "$DEMO_LABEL_KEY" || exit 1

    # Merge MR
    accept_mr "$mr_iid" || exit 1

    # Wait for ArgoCD sync
    wait_for_argocd_sync "${DEMO_APP}-${env}" "$argocd_baseline" || exit 1

    # Verify K8s state
    demo_action "Verifying label in K8s deployment..."
    assert_pod_label_equals "$env" "$DEMO_APP" "$DEMO_LABEL_KEY" "$DEMO_LABEL_VALUE" || exit 1

    demo_verify "Promotion to $env complete"
    echo ""
done

# ---------------------------------------------------------------------------
# Step 5: Cross-Environment Verification
# ---------------------------------------------------------------------------

demo_step 5 "Cross-Environment Verification"

demo_info "Verifying label propagated to ALL environments..."

assert_env_propagation "deployment" "$DEMO_APP" \
    "{.spec.template.metadata.labels.$DEMO_LABEL_KEY}" \
    "$DEMO_LABEL_VALUE" \
    "${ENVIRONMENTS[@]}" || exit 1

# ---------------------------------------------------------------------------
# Step 6: Summary
# ---------------------------------------------------------------------------

demo_step 6 "Summary"

cat << EOF

  This demo validated UC-C1: Add Default Label to All Deployments

  What happened:
  1. Added '$DEMO_LABEL_KEY: $DEMO_LABEL_VALUE' to services/core/app.cue
  2. Pushed CUE change only (no manual manifest generation)
  3. For each environment (dev, stage, prod):
     - Created MR targeting environment branch
     - Pipeline generated manifests (visible in MR diff)
     - Merged MR after pipeline passed
     - ArgoCD synced the change
     - Verified label appears in K8s deployment

  Key Observations:
  - Human only changed CUE (the intent)
  - Pipeline generated YAML (the implementation)
  - MR showed both changes for review
  - Label propagated to ALL environments

EOF

# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------

demo_step 7 "Cleanup"

demo_action "Returning to original branch: $ORIGINAL_BRANCH"
git checkout "$ORIGINAL_BRANCH" 2>/dev/null || true

demo_info "Feature branch '$FEATURE_BRANCH' left in place for reference"
demo_info "To delete: git branch -D $FEATURE_BRANCH && git push origin --delete $FEATURE_BRANCH"

demo_complete
