#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 <repo-dir> <mr-description-file>" >&2
    exit 1
fi

REPO_DIR="$1"
MR_DESCRIPTION_FILE="$2"

if [[ ! -d "$REPO_DIR" ]]; then
    echo "Repo dir not found: $REPO_DIR" >&2
    exit 1
fi

if [[ ! -f "$MR_DESCRIPTION_FILE" ]]; then
    echo "MR description file not found: $MR_DESCRIPTION_FILE" >&2
    exit 1
fi

: "${DEPLOY_ENV:?DEPLOY_ENV is required}"
: "${DEPLOY_BRANCH_PREFIX:?DEPLOY_BRANCH_PREFIX is required}"
: "${DEPLOY_MR_TITLE:?DEPLOY_MR_TITLE is required}"
: "${IMAGE_TAG:?IMAGE_TAG is required}"
: "${APP_NAME:?APP_NAME is required}"
: "${FULL_IMAGE:?FULL_IMAGE is required}"
: "${WORKSPACE:?WORKSPACE is required}"
: "${BUILD_NUMBER:?BUILD_NUMBER is required}"
: "${GIT_SHORT_HASH:?GIT_SHORT_HASH is required}"
BUILD_URL="${BUILD_URL:-unknown}"
: "${GITLAB_TOKEN:?GITLAB_TOKEN is required}"
: "${GITLAB_URL:?GITLAB_URL is required}"

cd "$REPO_DIR"

# Fetch and checkout target environment branch
git fetch origin "${DEPLOY_ENV}"
git checkout "${DEPLOY_ENV}"
git pull origin "${DEPLOY_ENV}"

# Create feature branch for this update
FEATURE_BRANCH="${DEPLOY_BRANCH_PREFIX}-${IMAGE_TAG}"
git checkout -b "${FEATURE_BRANCH}"

# L5: Sync app.cue from source repo (if exists)
if [ -f "${WORKSPACE}/deployment/app.cue" ]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "Syncing deployment configuration (L5)..."
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    mkdir -p templates/apps
    cp "${WORKSPACE}/deployment/app.cue" "templates/apps/${APP_NAME}.cue"
    echo "✓ Synced templates/apps/${APP_NAME}.cue"
fi

# L6: Update image tag in env.cue
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Updating image tag (L6)..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
./scripts/lib/update-app-image.sh "${DEPLOY_ENV}" "${APP_NAME}" "${FULL_IMAGE}"
echo "✓ Updated ${APP_NAME} image in env.cue"

# Stage CUE changes only - k8s-deployments CI will generate manifests
git add templates/apps/ env.cue 2>/dev/null || git add env.cue

# Check if update-app-image.sh and app.cue sync produced any staged changes.
if git diff --cached --quiet; then
    echo "No changes vs ${DEPLOY_ENV} - image tag already current. Skipping MR creation."
    touch "${WORKSPACE}/.no-changes-${BUILD_NUMBER}"
else
    # Commit with metadata
    git commit -m "${DEPLOY_MR_TITLE}

L5/L6 update from application CI/CD pipeline.

Changes:
- Synced templates/apps/${APP_NAME}.cue (if changed)
- Updated ${DEPLOY_ENV} environment image to ${IMAGE_TAG}

Note: Manifests will be generated by k8s-deployments CI.

Build: ${BUILD_URL}
Git commit: ${GIT_SHORT_HASH}
Image: ${FULL_IMAGE}"
fi

# Skip push and MR if the update block detected no changes.
if [ -f "${WORKSPACE}/.no-changes-${BUILD_NUMBER}" ]; then
    echo "Skipping push and MR creation - no changes detected."
    exit 0
fi

# Delete remote branch if it exists, then push fresh
git push origin --delete "${FEATURE_BRANCH}" 2>/dev/null || echo "Branch does not exist remotely"
git push -u origin "${FEATURE_BRANCH}"

# GitLab API credentials for MR operations
export GITLAB_URL_INTERNAL="${GITLAB_URL}"

# Close any open MRs superseded by this build (JENKINS-27)
./scripts/close-superseded-mrs.sh \
    "${DEPLOY_ENV}" \
    "${DEPLOY_BRANCH_PREFIX}" \
    "${FEATURE_BRANCH}"

# Create MR using GitLab API
./scripts/lib/create-gitlab-mr.sh \
    "${FEATURE_BRANCH}" \
    "${DEPLOY_ENV}" \
    "${DEPLOY_MR_TITLE}" \
    "$(cat "${MR_DESCRIPTION_FILE}")"
