apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-dev
  namespace: argocd
  labels:
    app: example-app
    environment: dev
spec:
  project: default

  # Source repository configuration
  source:
    repoURL: http://gitlab.gitlab.svc.cluster.local/example/k8s-deployments.git
    targetRevision: dev
    path: manifests/dev

  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  # Sync policy - automated for dev
  syncPolicy:
    automated:
      prune: true      # Delete resources not in git
      selfHeal: true   # Force sync when drift detected
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health check and status
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore HPA-managed replica count
