apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-stage
  namespace: argocd
  labels:
    app: postgres
    environment: stage
spec:
  project: default

  # Source repository configuration
  source:
    repoURL: http://gitlab.gitlab.svc.cluster.local/example/k8s-deployments.git
    targetRevision: stage
    path: manifests/stage/postgres

  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: stage

  # Sync policy - semi-automated for stage (manual approval via MR)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health check and status
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
